apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-deployment
  labels:
    app: publisher-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: publisher-service
  template:
    metadata:
      labels:
        app: publisher-service
    spec:
      volumes:
      - name: sftp-storage
        persistentVolumeClaim:
          claimName: sftp-volumeclaim
      containers:
      - name: publisher-service
        image: publisher
        env:
        - name: SFTP_PATH
          value: "/sftp"
        ports:
        - containerPort: 22
        volumeMounts:
        - mountPath: "/sftp"
          name: sftp-storage
        imagePullPolicy: Never