apiVersion: v1
kind: Service
metadata:
  name: publisher-service
spec:
  type: NodePort
  selector:
    app: publisher-service
  ports:
    - protocol: TCP
      port: 8180
      targetPort: 8080