apiVersion: v1
kind: Service
metadata:
  name: sftp-service
spec:
  type: NodePort
  selector:
    app: sftp-service
  ports:
    - protocol: TCP
      port: 30022
      targetPort: 22
      nodePort: 30022